name: osquery_exporter
arch: amd64
platform: linux
version: ${VERSION}
section: utils
priority: optional
maintainer: Stefan Maerz <104440170+stefanamaerz@users.noreply.github.com>
description: |
  Prometheus exporter for osquery query results.
  osquery_exporter runs osqueryi queries on each Prometheus scrape
  and exposes the results as Prometheus metrics.
homepage: https://github.com/stefanamaerz/osquery_exporter
license: Apache-2.0
contents:
  - src: osquery_exporter
    dst: /usr/bin/osquery_exporter
    file_info:
      mode: 0755
  - src: README.md
    dst: /usr/share/doc/osquery_exporter/README.md
    file_info:
      mode: 0644
  - src: changelog.Debian
    dst: /usr/share/doc/osquery_exporter/changelog
    file_info:
      mode: 0644
    packager: deb
deb:
  compression: zstd
